### ISSUE TITLE
Onduleur UPS

### ISSUE THREAD

**Issue by heuzef** [heuzef/Allo-GG#1]
Voir pour trouver une petite pile onduleur UPS adapté au PI Z comme par exemple : http://a.co/d/fIztwuS

L'objectif est de palier au problème de sous-tension mais également de permettre au PI Z de tenir le temps d'une coupure de courrant (~1H).

**Comment by kaeim6c** [comment]
Onduleur pas nécessaire car le risque de corruption de la carte SD, lors d'une coupure d'électrécité est limité car il y a très peu de coupures de courant, et le cout de remplacement d'une SD de 16go est faible (+/- 5€) via des sites chinois.
