### ISSUE TITLE
Impression 3D d'un boitier

### ISSUE THREAD

**Issue by heuzef** [heuzef/Allo-GG#11]
Réaliser un boitier en 3D sur mesure et en imprimer 2 grâce à une imprimante 3D.

**Comment by heuzef** [comment]
@kaeim6c  si tu es intéressé par cette partie, tu peux commencer à te créer un compte sur https://www.tinkercad.com et suivre les didacticiels :wink: 

Ensuite, voila le lien du projet 3D :

https://www.tinkercad.com/things/hjMSKTjyMB6-sizzling-krunk/edit?sharecode=Pq_lkjhOgdbRNVcC4Idaol67q77ha4CsRhuM7bMLv2s=

J'ai un contact qui peut nous imprimer les 2 boitiers :+1: 

Limite de taille d'impression **200mm³**

**Comment by kaeim6c** [comment]
Je vais commencer à rédiger un cahier des charges afin de faciliter et de structurer la création du boîtier Allo-GG. Un première ébauche, devrait être prête d’ici 1 semaine environ et permettra de discuter à partir d’une base existante.

**Comment by heuzef** [comment]
Après impression d'un prototype de la V1 et testé en  situation réel, une V2 à été conçu avec les différentes corrections.

https://raw.githubusercontent.com/heuzef/Allo-GG/master/allo-gg_case_v2/rendus/render4.png

Upload des fichiers sources OK : 5634e7e8698b9292bd5c84d69f0e90c13cc4ebfb
