### ISSUE TITLE
LED d'états

### ISSUE THREAD

**Issue by kaeim6c** [heuzef/Allo-GG#14]
Choisir 2 pins GPIO pour ajouter une led de couleur verte permettant de connaitre l'etat de fonctionnement du systeme. Cette led cette led demarrera en meme temps que le script de boot

**Comment by heuzef** [comment]
LED VERTE = Système opérationnel (boot.sh) <= À définir deux nouvelles broche

LED ROUGE = Mute en cours (mute.sh) <= Sur le relais de la sonnette

LED BLEU = Ouverture de la porte (open.sh) <= Sur le relais de la porte

**Comment by heuzef** [comment]
https://fr.pinout.xyz/pinout/

**Comment by Eclipse2212** [comment]
@heuzef Pourquoi deux "nouvelles" broches pour la LED verte?
Ok pour une pour envoyer le signal logique mais la seconde broche c'est la masse(GND) commune...

**Comment by heuzef** [comment]
OK ! Donc juste une nouvelle broche, la deuxième patte de la LED verte sera donc relié a la broche N°9 si j'ai bien compris ?

**Comment by heuzef** [comment]
ça m'arrangerais bien d'utiliser plutôt le GND 25 plutôt que le 9 vu qu'on à des GPIO dispos. Avec mes ptis câbles dupont ça sera bien plus propre ^^

**Comment by Eclipse2212** [comment]
Un pi à 5 ou 6 GND (toutes communes) donc tu peux y piocher comme ça t'arrange, juste qu'en général on utilise toujours une masse commune (plus propre)

**Comment by heuzef** [comment]
Ok la 14 donc, plus cohérent et proche donc mieux pour le GND :wink: 

Et pour le signal logique par contre ça coince ? On a utilisé les 2 seules alimentations en 3,3V :disappointed: 

Comment faire ?

**Comment by kaeim6c** [comment]
En utilisant un relais double au lieu de 2 relais simples, on libère une broche 3,3v et une broche ground. Cela permet d’alléger le câblage et d’alimenter un autre élément électronique si besoin

**Comment by heuzef** [comment]
Sauf que pas possible d'utiliser un seul relais double, à cause de la récupération des états justement.

**Comment by heuzef** [comment]
Du coup je pense que je vais choper le pin 12 (BCM 18) pour la LED verte, semble le choix le plus logique

**Comment by heuzef** [comment]
Testé en live avec @kaeim6c ^^

Donc nous utilisons le PIN 17 pour l'alimentation + le 12 pour la sortie logique pour récupérer son état. Il n'y à pas besoin de GND pour juste une LED @Eclipse2212  :wink:
