### ISSUE TITLE
Etat des broches GPIO via l'interface web

### ISSUE THREAD

**Issue by kaeim6c** [heuzef/Allo-GG#15]
Creer une section sur la page php permettant de connaitre l'etat actuel des fonctions. Peut etre utilise pour griser le bouton non actif (ex:sonette ou sourdine)

**Comment by Eclipse2212** [comment]
Au besoin, on peux lire les états dans `/sys/class/gpio`

**Comment by heuzef** [comment]
Voila les status sont récupérés et le bouton de la sonnette est unique et apparaît en fonction de l'état en cours.

Pour les status, je me suis bien pris la tête donc je suis reparti sur un truc plus sobre finalement. Je vais afficher virtuellement l’état des 3 LED physiques.

Pour la LED de la Sonnette c'est OK.

Il me manque encore la LED pour la porte, je devrais pouvoir trouver un moyen, même si pas simple a cause du délais très cours. À voir.

Pour la LED de status, j'ai besoin de connaître les nouvelles broches dédiés @kaeim6c :wink:

**Comment by heuzef** [comment]
Et voila pour la LED Bleu :) 17093e344848914b362a626db91034cae0d0a70f

Il ne reste plus que la LED Verte donc !

**Comment by heuzef** [comment]
> ⏳
> **En attente de résolution de l'issue https://github.com/heuzef/Allo-GG/issues/14**

**Comment by heuzef** [comment]
Clôture de l'issue #14 OK, nous avons pu tester le bon fonctionnement des LED Virtuelle avec @kaeim6c
