### ISSUE TITLE
Activation SSH avant l'installation

### ISSUE THREAD

**Issue by Eclipse2212** [heuzef/Allo-GG#16]
Serait-il préférable de rajouter une option pour installer raspbian directement en SSH sur le pi?

D'après le wiki, en mettant un fichier vide "ssh" dans le /boot lors de l'installation de la SD, le Pi démarre le daemon au démarrage avec les logins Pi/raspberry.

Cela pourrait être utile notamment pour les personnes ayant un support matériel limité (par exemple manque d'écran)

**Comment by heuzef** [comment]
Effectivement je ne connaissais pas cette fonction.

Reste cependant encore une contrainte, qui peux peut-être aussi être pré-configuré : la connexion au wifi.

Sans ça, impossible de se connecter en réseau ;)

Donc pour moi, cette fonction sera possible uniquement après résolution de l'issue N°9

https://github.com/heuzef/Allo-GG/issues/9

**Comment by heuzef** [comment]
> :hourglass_flowing_sand:
> En attente de résolution de l'issue #9

**Comment by heuzef** [comment]
Réglé en activant la fonction directement dans le script d'install. CF 5ea7be8118e46661b38aba7c9a4b32b7d74727ae
