### ISSUE TITLE
Créer une vérification récurrente de l'état des services

### ISSUE THREAD

**Issue by kaeim6c** [heuzef/Allo-GG#17]
si l'un des services (ip, apache, wiringpi) est inactif, la led verte doit s'éteindre. une verification se fera automatiquement toutes les heures.

**Comment by heuzef** [comment]
Script OK https://github.com/heuzef/Allo-GG/blob/master/scripts/check_services.sh

Patch d'ajout : echo '*/20 * * * * /bin/bash /var/www/html/scripts/check_services.sh > /dev/null' | crontab -u allo-gg -

Nous partons donc sur une exécution toutes les 20 minutes.

Le CPU monte à 50% max sur 3 sec en moyenne, c'est très raisonnable comme délais.

Reste plus qu'à tester voir si tout fonctionne correctement, je couperais le wifi pendant 30 min chez moi avant de le remettre pour surveiller le comportement de la LED d'etat ;)

**Comment by heuzef** [comment]
Le script est bien fonctionnel, mais y'a un souci avec l'execution du cron. Peut être juste un problème de syntaxe il faut que je prenne le temps de debuger et corriger ça.

**Comment by heuzef** [comment]
Je perd mes cheveux sur ce problème ... j'ai a peu prêt tout tenter avec cette !*@% de cron ...

Il s’exécute bien :+1: 
`Jan 27 17:33:01 allo-gg CRON[745]: pam_unix(cron:session): session opened for user root by (uid=0)
Jan 27 17:33:01 allo-gg CRON[749]: (root) CMD (root /bin/bash /var/www/html/scripts/check_services.sh >> /var/www/html/cron.log )
Jan 27 17:33:01 allo-gg CRON[745]: pam_unix(cron:session): session closed for user root
`

Va savoir pourquoi, le script ne produit rien, alors que lorsque je le lance à la main, pas de souci ...

**Comment by heuzef** [comment]
A tester : 

1. Script plus simple pour s'assurer que le problème ne viendrais pas du script finalement
2. Voir comment debuger cron, verbositer des log, etc
3. Mettre en place un bouton manuel pour l'instant

**Comment by heuzef** [comment]
C'est bon !!! 💪 C'était un simple problème de chemin absolu .... 😩

Cf commits 9e298512f82a737ca7eac9669a3feb3d083a1493  cf2e695a3affd05ede958f3c114b0457339a827a  14e86f931874146afb911a1843e4f6f958a374a5  pour le fix.

**Comment by heuzef** [comment]
Le script de verif est actuellement programmé pour s'executer toutes les 20Min.

J'ai testé sur la coupure de Apache. J'ai aussi testé sur l'arrêt de Wi-Fi. En rallumant le Wi-Fi, le module ce raccroche correctement sur le Wi-Fi sans problème :+1:
