### ISSUE TITLE
Ajout d’un script pour reconnecter le Pi automatiquement au Wifi

### ISSUE THREAD

**Issue by kaeim6c** [heuzef/Allo-GG#18]
Lors de longues périodes de fonctionnement, le Wifi du Pi a tendance à décrocher du réseau. Le problème étant que la reconnection peut se faire rapidement comme elle peut prendre plusieurs dizaine de minutes. Pour optimiser la disponibilité du module, il est question de créer un script qui vérifierait toutes les 5min que la connection Wifi est active et qui, le cas échéant, forcerait une reconnection.

**Comment by heuzef** [comment]
Dans mon cas j'avais imaginé intégrer cette fonction directement dans celui de vérification toutes les 20min. Ce qui me semble déjà vraiment pas mal. Les décrochage wifi ne sont pas censé arriver normalement.

**Comment by heuzef** [comment]
http://alexba.in/blog/2015/01/14/automatically-reconnecting-wifi-on-a-raspberrypi/

**Comment by heuzef** [comment]
C'est OK pour ça. Le script de verif va lancer un test de connexion, s'il echou, il va tenter de reconnecter le wifi. Si l'echec persiste, alors il déclenchera une alerte.

https://github.com/heuzef/Allo-GG/blob/master/scripts/check_services.sh#L48
