### ISSUE TITLE
Rediriger l’ecriture des logs sur la RAM pour protéger la carte SD

### ISSUE THREAD

**Issue by kaeim6c** [heuzef/Allo-GG#21]
Le but poursuivi est de prolonger la durée de vie de la carte SD fortement sollicitée par le raspbian pour écrire des logs, ce qui réduit la durée de vie de la carte SD.

Une petite explication ici: 
http://www.magdiblog.fr/divers/comment-prolonger-la-duree-de-vie-de-vos-cartes-sd-sur-raspberry-pi/

**Comment by heuzef** [comment]
Après plusieurs test de plusieurs solutions, nous ne pouvons pas le faire à la main à cause d'apache.

J'ai batailler quelques heures avec Ramlog sans succès, heuresement je suis tombé sur le projet MIT log2ram :)

Merci @azlux pour ça ! https://github.com/azlux/log2ram

https://github.com/heuzef/Allo-GG/commit/ebabbe849f95e9675e99e436fc4819bba0b6658c

Reste à s'assurer que ça fonctionne correctement après une réinstallation complète.

**Comment by heuzef** [comment]
Réinstallation complète effectué. Tous roule, Log2ram est correctement lancé.

Il va donc quotidiennement (grâce à cron) envoyé les log en Ram sur la SD, une seul fois par jours.

**Comment by azlux** [comment]
Happy to help !
