### ISSUE TITLE
Ajout clef SSH du Apple MAC sur Github

### ISSUE THREAD

**Issue by heuzef** [heuzef/Allo-GG#5]
Ajouter la clef public du PI Z sur Github pour permettre un clone via SSH : 

https://github.com/settings/ssh/new

Pour afficher la clef public : 
`cat ~/.ssh/id_rsa.pub`

Si besoin de générer une nouvelle clef : 

`ssh-keygen -t rsa`

**Comment by kaeim6c** [comment]
Problème SSH résolu pour le Mac
